version: '3.7'
services:
  redis:
    image: redis:alpine
    ports: #fdsssssssss
      - '6379'
    networks: #fdddd
      - backend
    deploy:
      replicas: 2
  db:
    image: postgres:alpine
    ports: #ffff
      - 5432:5432
    networks:
      - backend
    deploy:
      replicas: 2
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgres}'
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_DB: '${POSTGRES_DB:-practica}'

  visualizer:
    image: dockersamples/visualizer
    ports:
      - 8080:8080
    volumes: #rfrfrr
      - '/var/run/docker.sock:/var/run/docker.sock'
    deploy:
      placement:
        constraints: [node.role==manager]

networks:
  frontend:
  backend:
